#!/usr/bin/ruby
# frozen_string_literal: true

longest_streak = streak = 0

# -- Exit gracefully --
Signal.trap('INT') do
  puts "\nLongest streak: #{longest_streak}"
  exit 0
end

def print_header
  puts <<~TXT
    ----------------------------------------------------------
                          THE GIT GAME
    ----------------------------------------------------------
    Welcome! The goal of the git game is to guess committers
    based on their commit messages.

  TXT
end

def print_help
  puts <<~TXT
    ----------------------------------------------------------
                              USAGE
    ----------------------------------------------------------
    git game [extra git log options]
    EX: git game --after={2014-08-08}
    (This script already uses --no-merges and --pretty.
    For more valid options see: https://git-scm.com/docs/git-log)
  TXT
end

# -- Usage Text --
input = nil
if ARGV.count.positive?
  input = ARGV.shift

  case input
  when 'help', '--help', '-h'
    print_header
    print_help
    exit 0
  end
end

# -- Fetch Repository Info --
commit_shas = `git log --no-merges --pretty=%H -z #{input}`
              .split("\0")
              .shuffle
committers = `git log --no-merges --pretty=%aN | sort -u`
             .split("\n")

# -- Show welcome message --
system('clear')

print_header
puts "You're playing in a repo with #{commit_shas.size} commits and #{committers.size}"
puts "distinct committers.\n\n"

committers.each do |committer|
  puts committer
end

puts 'Ready? PRESS ENTER TO START PLAYING (Ctrl-C to quit)'
gets

system('clear')

# -- Game loop --
NUM_CHOICE = 4

commit_shas.each do |sha|
  puts `git show #{sha} --pretty='(%ar)%n%B' --shortstat`
  puts "\n\n"

  author = `git show #{sha} --pretty=%aN --no-patch`.strip
  choices = [author]
  choices += committers.reject do |name|
    name == author
  end.sample(NUM_CHOICE - 1)

  choices.shuffle.each_with_index do |name, index|
    puts "[#{index + 1}] #{name}"
  end

  guess = nil
  until guess.to_i.between?(1, NUM_CHOICE)
    print "Who wrote it (current streak: #{streak})? "
    guess = gets.strip
  end

  if choices[guess.to_i - 1] == author
    streak += 1
    puts 'Got it!'
  else
    streak = 0
    puts "Actually, it was #{author}."
  end

  longest_streak = [longest_streak, streak].max

  sleep 1
  system('clear')
end

puts <<~TXT
  Congratulations! There are no more commits in this repo!

  Longest streak: #{longest_streak}
TXT
exit 0
